language: cpp
compiler: gcc
dist: trusty

common_sources: &all_sources
  - ubuntu-toolchain-r-test
  - llvm-toolchain-trusty
  - llvm-toolchain-trusty-3.9
  - llvm-toolchain-trusty-4.0
  - llvm-toolchain-trusty-5.0
  - llvm-toolchain-trusty-6.0

addons:
  apt:
    sources: *all_sources
    packages:
    - python3
    - python3-pip
    - g++-8
    
#before_install:
#  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
#  - sudo apt-get update -qq

install: 
  - pip install conan --user
  #- sudo apt-get install -qq g++-8 cmake
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90

script: 
  #- conan profile new default --detect
  - conan remote add comunity https://api.bintray.com/conan/conan-community/conan 
  - conan remote list
  - mkdir build
  - cd build
  - cmake --version
  - conan install .. --build boost -s compiler=gcc -s compiler.version=8
  - cmake ..
  - make -C .
  - ctest .
  
