language: cpp
compiler: gcc
dist: trusty

addons:
  apt:
    packages:
    - python3
    - python3-pip
    
before_install:
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - python3 get-pip.py --user
  - pip install conan
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install: 
  - sudo apt-get install -qq g++-6 cmake
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90

script: 
  - conan remote add comunity https://api.bintray.com/conan/conan-community/conan 
  - mkdir build
  - cd build
  - cmake --version
  - conan install ..
  - cmake ..
  - make -C .
  - ctest .
  
